pipeline:
  agent: any
  environment:
    AZURE_STORAGE_ACCOUNT: "ssissg"
    AZURE_STORAGE_KEY: "+ZhT4GQg3hEKI8J3RxVb4tAHKfv0zqpvNGPCevB6UUnmwT6/HAd5U72dnWxWxYMoD52dCj3n/V8S+ASt6QWtCw=="
    AZURE_FILESHARE_NAME: "ssisfs"
  stages:
    - stage: Checkout
      steps:
        - git:
            branch: master
            url: https://github.com/JDivyansha/FirstCommit
    - stage: Upload SSIS Packages to Azure File Share
      steps:
        - script:
            sh: |
              az storage file upload-batch --source jenkinspipelinedemo1.yml --destination $AZURE_FILESHARE_NAME --account-name $AZURE_STORAGE_ACCOUNT --account-key $AZURE_STORAGE_KEY

